[package]
name = "rust-practice1"
version = "0.1.0"
edition = "2024"

[dependencies]
validator = { version = "0.19", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"                                       # エラーハンドリング用
