[package]
name = "section2-2-1"
version = "0.1.0"
edition = "2024"

[dependencies]
ron = "0.10.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.34"
toml = "0.8.20"
