[package]
name = "section2-1"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1.44.2", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
utoipa-swagger-ui = { version = "9", features = ["axum"] }
utoipa = { version = "5.3.1", features = ["axum_extras"] }
